### ISSUE TITLE
Implement /tierlist endpoint

### ISSUE THREAD

**Issue by dvsshadow** [NieR-Rein-Guide/nierrein.guide#4]
- [x] Quest, Arena, Weapons
- [x] List tiers (S/A/B, etc...) taking inspiration from [tiermaker](https://tiermaker.com/)

quick mockup by Insta 
![preview](https://cdn.discordapp.com/attachments/877530614138560603/880047011007721482/Tier_List_Design2_0.9.png)

**Comment by KeziahMoselle** [comment]
![image](https://user-images.githubusercontent.com/9168097/130330860-a4828dc6-44da-4442-93cd-7af745275139.png)
